
tasks:
  build-deps:
    #runner: razorci/openjdk:11-buster
    steps:
    - checkout
    - commands:
      - |
        sudo mkdir -p /opt/logzio-agent; sudo chown -R $USER: /opt/logzio-agent; mkdir -p /tmp/logzio; curl -fsSL 'https://github.com/logzio/logzio-agent-manifest/releases/latest/download/agent_linux.tar.gz' -o /tmp/logzio/agent_linux.tar.gz; tar -zxf /tmp/logzio/agent_linux.tar.gz --directory /tmp/logzio; bash /tmp/logzio/agent.bash --url=https://app.logz.io --id=3222d133-76b4-4a27-a3dd-6589addeefb8
